approvedGitRepositories:
  - '**'

compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: true

enableScripts: true

globalFolder: ../.yarn/berry

nodeLinker: pnp

npmRegistryServer: 'https://registry.npmjs.org'

npmScopes:
  atls:
    npmRegistryServer: 'https://registry.npmjs.org'

pnpEnableEsmLoader: true

preferReuse: true

yarnPath: .yarn/releases/yarn.mjs
